# this makefile also gets parsed by shell scripts
# therefore it does not support full make syntax and features
# edit with care

PACKAGE          = Asg_Lhapdf
PACKAGE_PRELOAD  = LHAPDF
PACKAGE_CXXFLAGS = 
PACKAGE_OBJFLAGS = 
PACKAGE_LDFLAGS  = 
PACKAGE_BINFLAGS = 
PACKAGE_DEP      = Asg_Boost
PACKAGE_TRYDEP   = TopRootCoreRelease
PACKAGE_CLEAN    = 
PACKAGE_NOOPT    = 0
PACKAGE_NOCC     = 1
PACKAGE_PEDANTIC = 1

include $(ROOTCOREDIR)/Makefile-common
